# Dify工作流导出器配置文件示例
# 复制此文件为 config.yaml 并根据您的实际情况进行配置

# 数据源配置 - 选择一种数据源方式
# 可选值: 'database', 'api'
data_source: api

# 数据库连接配置 (当data_source为'database'时使用)
database:
  # 数据库类型，目前支持 postgresql
  type: postgresql
  
  # 数据库连接信息 - 请修改为您的Dify数据库信息
  host: localhost
  port: 5432
  database: dify
  username: postgres
  password: your_password_here
  
  # 连接池配置
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  
  # SSL配置
  ssl_mode: prefer  # disable, allow, prefer, require
  
  # 表名配置 (如果Dify使用了自定义表名)
  tables:
    apps: apps
    workflows: workflows
    app_environment_variables: app_environment_variables
    workflow_nodes: workflow_nodes
    workflow_edges: workflow_edges

# API连接配置 (当data_source为'api'时使用)
api:
  # Dify API基础URL - 请修改为您的Dify API地址
  base_url: https://your-dify-instance.com/
  
  # API认证方式 - 支持三种认证方式：
  auth:
    # 方式一：Bearer Token认证（推荐）
    type: bearer  # bearer, basic, api_key
    token: 'your_api_token_here'  # 请填写您的API Token
    
    # 方式二：用户名密码认证（基本认证）
    # type: basic
    # username: your_username_here  # 您的Dify用户名
    # password: your_password_here  # 您的Dify密码
    
    # 方式三：API Key认证
    # type: api_key
    # api_key: your_api_key_here
    # api_key_header: X-API-Key  # API密钥头名称
  
  # API端点配置 - 所有API端点的完整配置
  endpoints:
    # 应用相关端点
    apps_list: '/console/api/apps'  # 获取应用列表
    app_detail: '/console/api/apps/{app_id}'  # 获取单个应用详情
    app_export: '/console/api/apps/{app_id}/export'  # 应用导出
    
    # 工作流相关端点  
    workflow_draft: '/console/api/apps/{app_id}/workflows/draft'  # 获取工作流草稿
    workflow_detail: '/console/api/workflows/{workflow_id}'  # 获取工作流详情
    
    # 环境变量端点
    environment_variables: '/console/api/apps/{app_id}/variables'  # 应用环境变量
    
  # API查询参数配置
  params:
    # 应用列表查询参数
    apps_list:
      name: ''  # 应用名称筛选，空表示不筛选
      is_created_by_me: false  # 是否只显示我创建的应用
      page: 1  # 默认页码
      limit: 50  # 默认每页数量
    
    # 分页配置
    pagination:
      default_page_size: 20  # 前端默认分页大小
      max_page_size: 100  # 最大分页大小
      api_page_size: 50  # API调用时的分页大小
  
  # 请求配置
  timeout: 30
  retry_count: 3
  retry_delay: 1

# 导出配置
export:
  # 默认导出格式
  default_format: yaml

# 日志配置
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR
  file: logs/app.log
  max_size: 10MB
  backup_count: 5
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

# 缓存配置
cache:
  enabled: true
  ttl: 300  # 缓存过期时间(秒) 